# A descriptive name for your workflow
name: Deploy Static Site to GitHub Pages

# Controls when the workflow will run
on:
  # Triggers the workflow on push events for the "main" branch
  push:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab on GitHub
  workflow_dispatch:

# Sets the permissions the workflow needs to deploy to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Defines the jobs that will run as part of the workflow
jobs:
  # A single job named "deploy"
  deploy:
    # Sets the environment for the GitHub Pages deployment
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    
    # Specifies the type of virtual machine to run the job on
    runs-on: ubuntu-latest
    
    # The sequence of tasks that will be executed
    steps:
      # Step 1: Checks out your repository's code so the job can access it
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Sets up the GitHub Pages environment
      - name: Setup Pages
        uses: actions/configure-pages@v5

      # Step 3: Uploads your website files as an artifact
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # Upload the entire repository's root directory. 
          # If your site is in a subfolder like "dist" or "build", change this path.
          path: '.' 

      # Step 4: Deploys the uploaded artifact to GitHub Pages
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4